Fix install instructions
Upgrading pip in the same command line with package install does not
use the new pip for remaining pkgs, and fastapi can fail to install
with older pip due to:

Collecting orjson<4.0.0,>=3.2.1; extra == "all" (from fastapi[all])
  Downloading https://files.pythonhosted.org/packages/3d/fa/53dba2273db6fa955bcfc250391c95dce0a27ec1f56cbec2e2a86a3107d6/orjson-3.5.3.tar.gz (742kB)
    100% |████████████████████████████████| 747kB 1.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-prs53cdv/orjson/setup.py'